# Generated by Django 3.0.7 on 2020-09-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=10)),
                ('text', models.CharField(max_length=500)),
                ('image', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'event',
            },
        ),
    ]
