# Generated by Django 3.0.7 on 2020-09-06 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0003_auto_20200906_1910'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attend',
            fields=[
                ('attend_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.User')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Event')),
            ],
            options={
                'db_table': 'attend',
            },
        ),
    ]
